export const ORGANIZATIONS_ENDPOINT = "/organizations"
export const CONDITIONS_ENDPOINT = "/search/v1/admin/pipelines/statements"
export const SHOW_ORGANIZATION_ENDPOINT = "/organizations/"
export const CREATE_PIPELINES_ENDPOINT = "/search/v1/admin/pipelines/"
export const TRACKING_ID_ENDPOINT = "/analyticsadmin/v1/properties/"